on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

name: Build and Release
jobs:
  build:
    name: Build NeXT
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Duet Web Control
        uses: actions/checkout@v4
        with:
          repository: Duet3D/DuetWebControl
          ref: 3.7-dev
          path: dwc-build

      - name: Build release asset
        run: |
          command -v rsync >/dev/null 2>&1 || {
            apt update && apt install -y rsync;
          }
          dist/release.sh next-release-${{ github.ref_name }} ${{ github.workspace }}/dwc-build


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: NeXT ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            dist/NeXT-${{ github.ref_name }}.zip
            dist/next.cps
            dist/next_post.py
            dist/milo-v1.5-std.mch

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: next-build-${{ github.sha }}
          path: |
            dist/*.zip
          retention-days: 7
